name: benchmark
description: A benchmark comparing sqflite & hive cache stores

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_cache_manager_hive:
    path: ../
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
