name: flutter_cache_manager_hive
description: flutter_cache_manager implementation for hive.
version: 0.0.9
homepage: https://github.com/vishna/flutter_cache_manager_hive

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  hashlib: ^1.12.0
  hive: ^2.2.3
  http: ">=0.13.0 <2.0.0"
  meta: ^1.1.8
  path: ^1.8.0
  path_provider: "^2.0.0"
  pedantic: "^1.8.0+1"
  rxdart: '>=0.26.0 <0.28.0'
  uuid:  '>=3.0.0 <5.0.0'